### ISSUE TITLE
Add import functionality

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#182]
*Originally reported by* **jobout12** at https://bugs.launchpad.net/bugs/1189666 (2013-06-10T22:48:04Z):

------------------------------------

Hello
I often take notes with notepad in windows and I can not import them into rednotebook to classify or complete.
Is this possible?

thnx

JB

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2013-06-11T13:04:54Z):

----------------------------------------

This is currently not possible, sorry. There are plans to add this
functionality though.
Am 11.06.2013 00:55 schrieb "bout" <email address hidden>:

> Public bug reported:
>
> Hello
> I often take notes with notepad in windows and I can not import them into
> rednotebook to classify or complete.
> Is this possible?
>
> thnx
>
> JB
>
> ** Affects: rednotebook
>      Importance: Undecided
>          Status: New
>
> --
> You received this bug notification because you are subscribed to
> RedNotebook.
> https://bugs.launchpad.net/bugs/1189666
>
> Title:
>   no txt import fonction
>
> Status in RedNotebook - A Desktop Journal:
>   New
>
> Bug description:
>   Hello
>   I often take notes with notepad in windows and I can not import them
> into rednotebook to classify or complete.
>   Is this possible?
>
>   thnx
>
>   JB
>
> To manage notifications about this bug go to:
> https://bugs.launchpad.net/rednotebook/+bug/1189666/+subscriptions
>

**Comment by jendrikseipp** [comment]
*Original comment by* **alan-m-hughes** (2014-11-06T10:05:33Z):

----------------------------------------

Can I echo this - it would be very useful (I use blip journal on android)

**Comment by jendrikseipp** [comment]
*Original comment by* **jendrikseipp** (2015-01-29T20:07:16Z):

----------------------------------------

As noted in https://answers.launchpad.net/rednotebook/+question/260985 it would be nice to be able to import backups as well.

**Comment by jendrikseipp** [comment]
*Original comment by* **dustinmoorman** (2015-02-27T14:56:40Z):

----------------------------------------

+1 This would be good, at least to support RNB's own backup type.

**Comment by jendrikseipp** [comment]
The current plan is to use external scripts for importing content into the RedNotebook month files.

**Comment by lminiero** [comment]
Is the RedNotebook month file format documented anywhere? I'd like to experiment with a basic lifeograph-to-RedNotebook converter, that I'd contribute if it turns out decent enough: it wouldn't be complete (I don't use the full features of lifeograph, and likely wouldn't use all the features in RedNotebook either), but it might be a good starting point for basic needs.

**Comment by jendrikseipp** [comment]
[It seems my mail got lost.]

That's a nice idea! Please have a look at the included help document (Ctrl-H). See rednotebook/storage.py to see how the RedNotebook YAML files are written.

**Comment by jendrikseipp** [comment]
Regarding the general issue of imports: I think it's better to have external tools that write RedNotebook files than to bake an import functionality into the app itself.

**Comment by lminiero** [comment]
Thanks for getting back to me! I eventually figured out the format was YAML-like, and did write a proof of concept (in nodejs) to translate a txt-exported lifeograph diary to RedNoteBook. It went mostly fine but I encountered some other issue that I now can't recall (it's been a few weeks). I'll get back to this next week, clean it up a bit and share what I did, as it's likely the issues were me doing something wrong.

**Comment by lminiero** [comment]
@jendrikseipp just FYI, you can find my proof of concept converter in this gist: https://gist.github.com/lminiero/c8b40bbadf57ce61e03aa9d18cbc41b5

It's tailored to how my diaries look like, and so there's stuff missing (I never include images, for instance). Besides, it's based on how I structure my diaries in terms of sections/subsections too, which may be different for others. That said, it "works".

I couldn't find a 1-1 translation pattern for everything, though, which is probably caused by my poor knowledge of the Rednotebook syntax (apologies for that!), and in some cases, where a translation existed it was problematic to enforce. Just to list a couple of examples:

1. in lifeograph, putting some text in hashtags (e.g., `#I'm special!#`) highlights it with a different background color; I haven't found a similar syntax in Rednotebook, although applying the translation would likely be quite complex (how to differentiate text to be highlighted from, e.g., a hashtag in a url?)
2. I seem to be missing a way to do unordered and ordered lists as well: in lifeograph, a tab followed by an asterisk or a number trigger both, but tinkering with Rednotebook I haven't found any obvious way of doing either;
3. lifeograph also uses square brackets and custom values in it to draw checkboxes: e.g., `[ ]` is an incomplete activite, `[~]` is a pending one, and so on; I couldn't find an equivalent here either, if available;
4. emph and bold text is one of the instances where a translation exists, but is hard to enforce: specifically, lifeograph uses `_` where rednotebook uses `//` for emph, whereas lifeograph uses a single asterisk instead of two to wrap bold text; I didn't translate those, though, due to the potential ambiguity in parsing the text (e.g., underscores could be part of some other text, and not necessarily be a trigger for an emphasis)

Apart for that, from a quick glance of a few items, the translation seemed ok in preview mode, even though there are instances where two separate lines in edit mode are collapsed in one when showing the preview. I'll keep on updating the gist as I learn more, so that I can hopefully be of help for anyone thinking of migrating: once it's decent enough, I can turn it into a repo people can refer to.

Hope this helps!

**Comment by lminiero** [comment]
And obviously I found some answers in the meanwhile looking at the CTRL+H help page you mentioned... sorry for the noise on that!

**Comment by jendrikseipp** [comment]
Thanks for sharing! I agree that it would be good to turn this into a repo at some point.

**Comment by jendrikseipp** [comment]
Let me close this issue, since import functionality is not planned for RedNotebook. Instead, we will collect external tools that convert other formats into RedNotebook YAML files.
