### ISSUE TITLE
Will rednotebook be included in Debian Stretch?

### ISSUE THREAD

**Issue by nikolas-n** [jendrikseipp/rednotebook#319]
I guess it's more of a question, if it's not suitable for here, delete it. I was really disappointed that it's not yet included...

**Comment by jendrikseipp** [comment]
I recently found out that it can't be included since it depends on 
python-webkit which is not included in Debian Stretch. I'm currently 
working on switching from python-webkit to the new python-gi webkit 
bindings. However, I think Debian Stretch is already feature-frozen so I 
guess even the next RedNotebook release will not be included.

**Comment by nikolas-n** [comment]
What a pity. Thanks for answering. What workaround do you suggest? Install python-webkit anyway?

**Comment by jendrikseipp** [comment]
If it works, I'd use python-webkit. If it doesn't, you'll have to wait 
for the new RedNotebook version and find a way to install it.

**Comment by nikolas-n** [comment]
Cool, thanks a lot!

**Comment by lszyba1** [comment]
Cross Reference to mailing list, with instructions on how to download rednotebook on debian stable (while its missing from repository)
https://lists.launchpad.net/rednotebook-users/msg00141.html
