### ISSUE TITLE
Help on formatting?

### ISSUE THREAD

**Issue by andy-twosticks** [jendrikseipp/rednotebook#323]
Can we have some more information on the formatting standard Rednotebook uses? It seems to be a bit like Markdown, but different.  (Which is my one niggle about it, but, that's my problem.)

For example, I seem to be able to create tables using something similar to Pandoc's "pipe format tables" ... but I can't see anything in the help or on the website about that; I just found that by accident.

Based on a comment you made on your FAQ, I think you are using something called "txt2tags"? But there doesn't appear to be a reference for that in English; the most I can find is a page of examples [here](https://mostlylinux.wordpress.com/textanddocument/txt2tagscheatsheet/#table). 

A complete reference for formatting in edit mode would be a genuine boon to your users (in my opinion).  If you don't feel the need or have the time, maybe put a link somewhere to the txt2tags page, if that is what you are using?

**Comment by jendrikseipp** [comment]
Thanks for the feedback. I agree that the link to txt2tags is rather 
hidden in the integrated help document. Here are some links to bring you 
up to speed:

http://txt2tags.org/
http://txt2tags.org/markup.html

In the future, it would be nice to support markdown. However, this might 
be tricky since we want to be backwards compatible (i.e., support the 
old markup that can be inserted via buttons in RedNotebook as well) and 
provide export options to LaTeX (most markdown tools only export to HTML).

**Comment by andy-twosticks** [comment]
Thanks.

If you want to follow through on Markdown support, then Pandoc might be an option, since it _does_ support LaTex.  Also, it's configurable, so you can choose what markdown it recognises.

It's written in Haskell, although I believe there are Python bindings.   Not sure if that would be compatible with you.

**Comment by DivineDominion** [comment]
Regarding Markdown detection, could it hurt to store as `.md` or `.md.txt` instead of `.txt` in case users don't want to mass-migrate their markup? The file extension is about the only thing we have to differentiate text files.

**Comment by jendrikseipp** [comment]
I think the best option would be to remain backwards-compatible to txt2tags, i.e., when converting text to HTML, transform the txt2tags markup to markdown and then convert the markdown to HTML. The filenames should not have to change for this.
