### ISSUE TITLE
Better Indentation Functionality (Also Documentation

### ISSUE THREAD

**Issue by levihilton** [jendrikseipp/rednotebook#342]
I wish there was a way to better indent paragraphs, first lines, etc. without changing other things such as making it bold or something.  If this is already implemented, I feel like it would be a good idea to set up a portion of the readme directly to formatting so that we can easily see a list of all the text manipulations you can make.

**Comment by jendrikseipp** [comment]
Indenting a line turns it into a quote. This is due to the txt2tags markup language that RedNotebook uses. I'm considering using Markdown instead, but probably allowing some txt2tags markup for backwards compatibility, so I would recommend to only use the markup that's available via the "Insert" and "Format" menu items.
