### ISSUE TITLE
Windows: Preview opens external browser in RedNotebook 2.x

### ISSUE THREAD

**Issue by wza77** [jendrikseipp/rednotebook#369]
After installation of RedNotebook 2.3 on Windows10 I run into the issue that there is no preview mode available in the program itself. It will only preview in a browser, which is nice, but highly inconvenient while searching and viewing the notebook entries.
![screencapture](https://user-images.githubusercontent.com/32361609/30966336-d5f8bda6-a458-11e7-858f-4fcbdfc4b78e.PNG)

**Comment by jendrikseipp** [comment]
I agree. Unfortunately, the embedded browser that RedNotebook uses on other operating systems (WebkitGTK) does not run on Windows. As far as I can tell, the best solution to this issue is using the Chromium Embedded Framework on Windows. It will require quite a bit of work though.

**Comment by wza77** [comment]
Thanks for your quick response.
As this might take some time, could you make the last stable windows 1.x release available for download.
This older version was working fine for me, but I don't have the installer anymore and I can't find it on https://github.com/jendrikseipp/rednotebook/releases/

Thanks in advance, 
Wouter

**Comment by jendrikseipp** [comment]
Here you go: https://sourceforge.net/projects/rednotebook/files/

**Comment by wza77** [comment]
Thanks!

**Comment by media1mogul** [comment]
Have the same issue.  I hate to roll back.  Thanks this helped though.

**Comment by vulcanmeister** [comment]
I don't like to roll back either, but I really prefer the "in-program" preview mode. I love RedNotebook and use it every day. Will try the 1.15 v since my needs are simple. Would of course like to see this feature eventually returned in the latest version Thanks!

**Comment by ericliret** [comment]
Hello
Is it possible to choose another browser (like firefox instead of Internet Explorer) somewhere in the options ? If yes, could you please indicate me where the modification has to be done ?
Thanks!

**Comment by jendrikseipp** [comment]
RedNotebook uses the system's default browser. You'll have to choose a different default in your system's preferences.

**Comment by Zaphod2012** [comment]
Just downloaded the 2.7 Beta and have been playing with it.
Running Windows 7 Professional with Service Pack 1, and all seems to be working great :)

I used to keep web clippings (.png and .jpg) of movie stars and other celebrities' obituaries in a folder and link to them in my RedNotebook, but after losing the ability to view them in the app, have stopped saving the pics - Now I can go back to it!

Thank You so much for the update, Jendrik :)

**Comment by jendrikseipp** [comment]
Thanks for testing! I just merged support for internal previews on Windows in #414. It will be part of RedNotebook 2.8. Adding back the word clouds is #415.

**Comment by media1mogul** [comment]
THUMBS UP!



*From:* Jendrik Seipp <notifications@github.com>
*Sent:* Thursday, November 15, 2018 4:06 AM
*To:* jendrikseipp/rednotebook <rednotebook@noreply.github.com>
*Cc:* media1mogul <mike@reekie.us>; Comment <comment@noreply.github.com>
*Subject:* Re: [jendrikseipp/rednotebook] Windows: Preview opens external
browser in RedNotebook 2.x (#369)



Thanks for testing! I just merged support for internal previews on Windows
in #414 <https://github.com/jendrikseipp/rednotebook/pull/414>. It will be
part of RedNotebook 2.8. Adding back the word clouds is #415
<https://github.com/jendrikseipp/rednotebook/issues/415>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jendrikseipp/rednotebook/issues/369#issuecomment-438968206>,
or mute the thread

**Comment by wza77** [comment]
Sorry for the late reply, but I also just tested the beta version and it seem to work fine for me too.
Thanks!
