### ISSUE TITLE
Wishlist - console text export

### ISSUE THREAD

**Issue by biffster** [jendrikseipp/rednotebook#397]
Hey there! Great work on rednotebook, it simply keeps getting better and better! I have a feature request that mainly benefits Linux users: a way to export a text entry from the console. e.g. instead of starting up the rednotebook window at all, a user types something like:

rednotebook --export=text --date=12/23/2017

rednotebook can just write the output to stdout, and the user can pipe that to whatever they want for whatever processing they want.

**Comment by jendrikseipp** [comment]
I think this functionality could be provided by an external script. The script should probably accept the path to a RedNotebook journal directory and a date and then write the contents of that date to stdout. Maybe a tool for reading YAML files could help here (like https://github.com/mikefarah/yq). Otherwise, you could reuse the code that RedNotebook uses for reading YAML files (in rednotebook/storage.py). If you get around to writing such a script, feel free to post it here or send it to me for others to use.
