### ISSUE TITLE
Adding weekday template selects wrong day

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#416]
From https://answers.launchpad.net/rednotebook/+question/676310:

Since upgrading to version 2.8 the 'This Weekday's Template' is not working. The days do not matchup.

For instance - today is Thursday. When I go to insert 'This Weekday's Template' it comes up as Wednesday. This is what it goes to insert:

```
=== It's Wednesday ===
$date$
====================
```
I have checked the template files to verify that they are correct. the File 4.txt is the Thursday file, it's contents are:
```
----------------- 4.txt file contents ----------------------------------
=== It's Thursday===
$date$
====================

-------------------------------------------------------------------------------
```
I have noticed this since upgrading to 2.8 last Friday.
[...]
I just un-installed 2.8 and re-installed 2.6.1 and the problem has gone away.

**Comment by jendrikseipp** [comment]
I was able to reproduce this in the Windows version, but the issue does not happen on Linux. I'll look into this.

**Comment by Staals** [comment]
Hello,
I have a similar, but different issue on Linux (v2.7). Since the update from what I think was 2.6.1, rather than selecting the weekday template for the weekday selected in the journal, RedNotebook selects only the template for the current weekday. So for instance, today is Monday 26/11. When I select Saturday and click insert template, I get Mondays template.  I use the program as an activity log, so I often need to insert templates for past days. Was the old situation unintended behavior? Or is the new one?
