### ISSUE TITLE
Support 7zip files

### ISSUE THREAD

**Issue by trymeouteh** [jendrikseipp/rednotebook#447]
Rednotebook works by opening folders but I and I believe many would like to have our journals as a single file. Here is why I would like to suggest having 7z file support.

**Compression**
You will be able to compress your journal size

**More Portable**
It will be a single file, not a directory

**Encryption**
7z files support encryption which allows you to make your journal unreadable without the password you set for the file. This add security and privacy to your journal.

**Universal File**
7zip files can be opened using many programs such as 7zip, peazip and more and you can access your journal without rednotebook.

**No Need To Create Encrypted File Type**
No need to create a filetype for RedNotebook that has good encryption and to ensure it is secure, just add 7zip support into RedNotebook.

**Comment by FearlessPotatoKing** [comment]
Wouldn't the file have to be unzipped/zipped/decompressed/compressed each time that you close and open RedNotebook? If it takes 4-5 seconds to do it each time that really adds up to a lot of wasted time when you think about the long term. I have been using Rednotebook for journaling purposes since 2014, sometimes i write just 1 entry, sometimes i open up the app multiple times a day to add a note or to add a picture, etc. It would be really frustrating if each time i went to open/close the application it would take 4-5 seconds longer to open/close.  Especially when you multiple it out over a span of multiple years. 

-If you need encryption, you can create a veracrypt container and place your journal files inside there. 
-I have had zero issues with copying the entire directory to move between computers. 
- I regularly use 7zip command line utility to create encrypted compressed backups of my .rednotebook folder that i place on an external hard drive/my phone in case of data loss. 

While this might have some benefits to you, it would be a big negative for people that don't want this feature.

**Comment by trymeouteh** [comment]
A journal is nothing but text files, so for a computer to have to compress and decompress the file will not take long, and you could use normal compression instead of ultra if you want less compression.

**Comment by nvdl** [comment]
I think that it is better to use a database then that supports these functions on the fly.
For example: https://mariadb.com/kb/en/encryption-hashing-and-compression-functions/

**Comment by jendrikseipp** [comment]
Using 7zip files is an interesting idea, but I don't think the pros (encryption, single file, compression) outweigh the cons (backwards incompatible, implementation work, 7zip dependency, read/write time overhead).
