### ISSUE TITLE
Calendar/Search panels in 2.11.1 missing 3 characters on left side in Ubuntu

### ISSUE THREAD

**Issue by hollandnumerics** [jendrikseipp/rednotebook#449]
### Versions

RedNotebook version (make sure you have the latest version):
2.11.1

Operating system and version:
Linux Mint 19.2 (Ubuntu 18.04)

### Expected behavior
Calendar/Search panel fully visible (correct in Windows 10)

### Actual behavior
Calendar/Search panel missing 3 characters on left side (incorrect in Linux Mint 19.2)

![image](https://user-images.githubusercontent.com/6469571/66202259-35e58900-e69d-11e9-8e26-1a9e4e467609.png)

**Comment by jendrikseipp** [comment]
You should be able to simply move the line between the calendar and the text field to the right.

**Comment by hollandnumerics** [comment]
Thanks, that worked fine!

Please could this information be added into the Help web page? Without it users may decide to use something else.

**Comment by jendrikseipp** [comment]
Ideally, I'd like to get the default width for the left panel right. Could you please perform the following steps?
* move the slider as far to the left as possible so that everything still looks fine (i.e., the whole calendar and the three buttons above are completely visible)
* close RedNotebook
* post the value of leftDividerPosition from $HOME/.rednotebook/configuration.cfg here

**Comment by hollandnumerics** [comment]
Rednotebook 2.11.1 - minimum width of fully readable left panel:
Windows 10: leftDividerPosition=201
Linux Mint 19.2: leftDividerPosition=235

I suspect the differences were affecting the default layout!

Hope this is helpful..............Phil
