### ISSUE TITLE
Question: Design decisions for choosing per-month YAML file format for journal storage

### ISSUE THREAD

**Issue by pfalcon** [jendrikseipp/rednotebook#530]
I'd think this would be a FAQ, but looking thru mailing list https://lists.launchpad.net/rednotebook-users/ or searching for "YAML" here in issues doesn't turn up much relevant stuff. So, let me try to ask a question here, and hope it wasn't well discussed here (and let me do it here, as the mailing list doesn't seem to be too active and requires more effort to subscribe/browse).

Anyway, something I was find nonetheless is the message https://lists.launchpad.net/rednotebook-users/msg00060.html :

>>  * Files are stored as text (even if it is a baroque format).

So, it's not just me. People find current file format of RedNotebook "baroque". The answer from the answer is however only more worrying:

> That's true. I might reconsider the format in the future and switch to json which should be both simpler and faster.

So, why not use the natural plain-text format, where 1 file == 1 day? Benefits are obvious: easily syncable/manipulable even without RedNotebook "frontend". For example, "Android client" is a plaintext editor on Android pointing into Dropbox (or any other sync app) directory. Stories like https://answers.launchpad.net/rednotebook/+question/675433 would happen with 1/100th probability and 1/30th impact (assuming the scale is linear; for me, losing a WHOLE MONTH of entries would mean instant sending of the app to /dev/null).

Drawbacks? Well, I can only imagine following logic: "Just imagine, that's 3650 files for 10 years! And 36500 for a century! Those must be slow to scan, etc, etc." Well, 3650 files is a trivial number. 36500 is less so. On a modern hardware (GBs of RAM, SSD) it may take a whole second to scan. Which is long, but should be sustainable, and after first scan, likely will be cached in those GBs of RAM.

So, why?

Thanks for possible response.

**Comment by jendrikseipp** [comment]
The design stems from the fact that earlier RedNotebook versions stored tags for a day (with subtags) separately from the main text entry for each day. Therefore, I chose a structured format, i.e., YAML, for this task. I could have used a separate YAML file for each day, but probably thought that this might be too slow. Since then, #hashtags have been introduced and the special tags have been deprecated. So, yes, now storing each day's text in a separate file without any YAML markup would be feasible. I'd definitely be interested in seeing a benchmark that compares how fast it is to open a large journal (let's say 10 years of entries with 10 sentences for each day) with the current format versus storing each day in a separate file. If the timing for the latter is good, I'd consider switching to this format. I'll close this for now since I answered the question, but feel free to reopen it once anyone has hard data on how fast the two approaches are.

**Comment by pfalcon** [comment]
Thanks for the reply, understood!

I agree that seeing benchmarks would be nice. But the biggest concern is still ease of data accessibility and processing (e.g. syncing), so I went with an app which stores an entry per file.
