### ISSUE TITLE
Default language for spell check

### ISSUE THREAD

**Issue by simone-romiti** [jendrikseipp/rednotebook#587]
At startup spell check is enabled using the system language. I'd like to set a different one to be the default, in order to not modify it manually each time.
I report that the manual change does not affect the .log file, and in the .cfg one can only set the "spellcheck" variable to be 0 or 1.

**Comment by jendrikseipp** [comment]
The help document shows how to change the language of the application. I think it should also change the spell check language:

**Language**

If you want to change RedNotebook's language, setting the environment variable LANG (Linux) or LANGUAGE (Windows) to a different language code should be sufficient. Language codes have e.g. the format "de_DE" or "de_DE.UTF-8" (German). To set the language to English you can also set the code to "C". Before you change the language make sure you have the required language packs installed. Otherwise an error will be shown.

On Linux, start a terminal and call `LANG=de_DE.utf8 rednotebook`. The language change will be gone however once you close the terminal.

On Windows, set or create a LANGUAGE environment variable with the desired code:

* Right-click My Computer and click Properties.
* In the System Properties window, click on the Advanced tab (Windows XP) or go to Advanced System Settings (Windows 7).
* In the Advanced section, click the Environment Variables button.
* Click the New button and insert LANGUAGE at the top and e.g. de or de_DE or de_DE.UTF-8 (use your [language code http://en.wikipedia.org/wiki/ISO_639-1]).

**Comment by simone-romiti** [comment]
Dear @jendrikseipp ,
I understand your solution, but that's not what I had in mind. You modify a global variable (LANG in Linux), but it's not permanent and you have to do it each time. The feature I would like is to set it once and for all, so that I don't have to bother at each startup. It would be nice being able to set in a field of the "Preferences" window.

By the way, I tried your solution but it doesn't work. I get the following output:
```
Starting RedNotebook from the source directory
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 9, in <module>
    journal.main()
AttributeError: module 'journal' has no attribute 'main'
```

**Comment by jendrikseipp** [comment]
What you can do is to create a custom program shortcut for RedNotebook. The default shortcut that gets installed when you install the deb package calls "/usr/bin/rednotebook". In your custom shortcut, you can call "LANG=de_DE.utf8 /usr/bin/rednotebook".
